name: extended_shared_preferences
description: Implements SharedPreferendes of Android and NSUserDefaults of iOS in Flutter.
version: 3.0.0
homepage: "https://github.com/MarloKessler/flutter-extended_shared_preferences"

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.marlokessler.sharedpreferences
        pluginClass: SharedpreferencesPlugin
